/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Play Again': '重玩',
    'Red': '红色',
    'Green': '绿色',
    'Blue': '蓝色',
    'Unlock blue': '解锁蓝色',
    'Unlock cyan': '解锁青色',
    'Unlock green': '解锁绿色',
    'Unlock magenta': '解锁品红色',
    'Unlock red': '解锁红色',
    'Unlock yellow': '解锁黄色',
    'Unlocks': '解锁',
    'unspent light': '未消耗的光',
    'Win the game!': '通关游戏！',
    'You are collecting': '您正在收集',
    'You have': '你有',
    'ALWAYS': '一直',
    'Loading...': '加载中...',
    'Main Prestige Tree server': '原版声望树',
    'Keep Going': '继续前进',
    'Exit Early': '提前退出',
    'Get more color': '获得更多颜色',
    'Hover to Charge Battery': '将鼠标悬停给电池充电',
    'Double Slit Experiment': '双缝实验',
    'Currently': '当前',
    '\"Corpuscular theory\"': '“微粒说”',
    'color energy': '色彩能量',
    '\"Double Slit Experiment\"': '“双缝实验“',
    '\"Wave Theory\"': '“波动理论”',
    '\"Alhazen\"': '“阿尔哈曾”',
    '\"Emission theory\"': '“发射理论”',
    'buyable.': '可买的。',
    'Finish': '完成',
    'levels': '等级',
    'Milestone Gotten!': '里程碑已达成！',
    'passively increases color gain': '被动地增加色彩增益',
    'Next at 4 each of red and green light': '下一个在红色和绿色光分别为4时',
    'Red light\'s effects are based on τ instead of 𝜋': '红光的效果是基于τ而不是𝜋',
    'Start': '开始',
    'The Modding Tree Discord': '模型树Discord',
    'Yellow': '黄色',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'OFF': '关闭',
    'ON': '打开',
    'SHOWN': '显示',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    '\"Newton\"': '“牛顿”',
    'Alhazen': '阿尔哈曾',
    'Buy Max': '购买最大',
    'automates mechanics': '自动化机械',
    'Automatically purchase upgrades': '自动购买升级',
    'Batteries act as if they\'re being charged for an extra quarter second for each secondary colored light': '电池就像为每个次级彩色灯充电了额外的四分之一秒一样',
    'by thepaperpilot': '由paperpilot',
    'Cyan': '青色',
    'Next at 9 each of green and blue light': '下一个在绿色光和蓝色光分别为9时',
    'Next at 9 each of red and green light': '下一个在绿色光和红色光分别为9时',
    'Allow bulk completion of up to 10 light at once': '一次允许批量完成多达10光',
    'Divide goal by amount of secondary light': '将目标除以次要光的数量',
    'Each point of secondary colored light gives a free': '次级彩色光的每个点都提供了一个免费',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Wave Theory': '波动理论',
    'Get sqrt(red light) more batteries': '多拿一节(红光)电池',
    'Color energy gain is multiplied by 5 raised to the amount of unspent light + 1': '色彩能量增益乘以5，即未消耗光的数量 +1',
    'Automatically purchase buyables': '自动购买可买项', 
    'Rebuyable. Double color energy gain.': '可再次购买。双倍色彩能量增益。',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '你用了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Battery cap is multiplied by number of': '电池上限乘以数字',
    'Half the goal for each unlocked battery + 1': '目标的一半，每个解锁电池 +1',
    'If this takes too long it means there was a serious error!': '如果这花费了太长的时间，这意味着有一个严重的错误!',
    'improves color energy gain directly': '直接提高色彩能量增益',
    'Increase color energy base gain by 1.': '增加色彩能量基础增益1。',
    'light': '光',
    'Lit': '光之树',
    'upgrade.': '升级.',
    'unlocks various useful upgrades': '解锁各种有用的升级',
    'unlocks batteries that actively increase base gain': '解锁电池，积极增加基础增益',
    'Start gathering color energy to produce a new light': '开始收集色彩能量以产生新的光',
    'Add a free level to': '添加一个免费等级到',
    'Corpuscular theory': '微粒说',
    'color energy per second': ' 色彩能量每秒',
    'Please check the Discord to see if there are new content updates!': '请查看Discord，看看是否有新的内容更新!',

    //原样
    'The Paper Pilot Community Server': 'The Paper Pilot Community Server',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Offline Time: ": "离线时间: ",
    "Show Milestones: ": "显示里程碑：",
    "Multiply color energy gain by ": "将色彩能量增益乘以",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Currently: ": "当前: ",
    "Raise battery cap to ": "提高电池上限到 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    " and unlock a battery": "并解锁一个电池",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)e(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Cost\: (.+) color energy$/, '成本：$1 色彩能量'],
    [/^Goal\: (.+) color energy$/, '目标：$1 色彩能量'],
    [/^Raise battery cap to ([\d\.,]+)$/, '将电池上限提高到 $1'],
    [/^Raise battery cap to ([\d\.,]+) and unlock a battery$/, '将电池上限提高到 $1 并解锁一个电池'],
    [/^([\d\.]+) Light$/, '$1 光'],
    [/^([\d\.]+) light$/, '$1 光'],
    [/^([\d\.]+)s$/, '$1 秒'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);